steps:
  - id: 'build-docker-image-for-ipl'
    waitFor: [ '-' ]
    name: 'gcr.io/cloud-builders/docker:20.10.3'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        cd app/        
        docker build -t gcr.io/$PROJECT_ID/app:latest .
        docker push gcr.io/$PROJECT_ID/app:latest

# Stored for caching purposes
images: [
    'gcr.io/$PROJECT_ID/app:latest',
]

timeout: 1200s # 20 minutes

options:
  machineType: 'E2_HIGHCPU_8'
